name: Deployment

on: push

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing.."
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploying.."
      if: github.ref == 'refs/heads/master'
