name: Deployment

on: push

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing...."
  BuildAndDeploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploying.."
