name: Deployment

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing...."
  
  testing1:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "Testing 1...."
  
  build-and-deploy:
    name: Build and deploy
    if: github.ref == 'refs/heads/master'
    needs: [testing, testing1]
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploying.."
