name: Deployment

on: push

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - if: github.ref == 'refs/heads/master'
    - run: echo "Deploying..."
