name: CI-PULL-REQUEST

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest   
    steps:

      # may or may not have a name, it's quite self-descriptive
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: |
          docker-compose build
          docker-compose up -d
          cd tests
          npm install
          npm test
          
    # steps:
    # - uses: actions/checkout@master
    # - name: Publish to Registry
    #  uses: elgohr/Publish-Docker-Github-Action@master
    #  with:
    #    name: dagandersen/d3v0ps-dr3ng3n3
    #   username: ${{ secrets.DOCKER_DAG_TEST_USER }}
    #    password: ${{ secrets.DOCKER_DAG_TEST_PASSWORD }}
    #   workdir: backend
    #     # dockerfile: backend/Dockerfile
