name: Pull Request

on: pull_request

jobs:
  eslint-backend:
    name: ESLint (Backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd backend
          npm install
          ./node_modules/.bin/eslint .
                               
  eslint-frontend:
    name: ESLint (Frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd frontend
          npm install --no-optional # --no-optional flag is set to fix this error: https://bit.ly/2VmFFcm
          ./node_modules/.bin/eslint .

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker-compose build
          docker build -t minitwit-simulator-integration-test ./tests/simulator-integration-test -f ./tests/simulator-integration-test/Dockerfile
          docker-compose up -d --force-recreate
          docker run --network=minitwit-network minitwit-simulator-integration-test

#  e2e-tests:
#    name: E2E tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          cd tests
#          npm install
#          npm test

  simulator-tests:
    name: Simulator tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker-compose build
          docker build -t minitwit-simulator ./tests/simulator -f ./tests/simulator/Dockerfile
          docker-compose up -d --force-recreate
          sleep 10
          docker run --network=minitwit-network minitwit-simulator
